[project]
name = "mcp-rpa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.23.1",
    "mcp[cli]>=1.5.0",
    "pyautogui>=0.9.54",
    "pyperclip>=1.9.0",
    "streamlit>=1.44.0",
]
